# Foundations {-}

I will outline my findings and my decisions for my first and second step below, and will address the third step across multiple pages due to the volume of information required to adequately achieved the goal of step 3.



## What is 'great', and what does it mean for a country to be great? {-}

Searching 'great' in Merriam-Webster's online dictionary at this link[https://www.merriam-webster.com/dictionary/great] (accessed on 11/16/2022) generates a variety of results:

  * 3 parts of speech
    * Adjective (with the most uses of the word 'great')
    * Adverb
    * Noun
    
There are a lot of options, so let's go to the basics. 'Make America Great Again' speaks to the qualities of the US as a country, and how that its quality has declined since its peak. With this in mind let's begin by removing the use cases that are least likely to be applicable in this setting. 

  * Great as a noun and as an adverb can be dismissed immediately, as we are looking for an adjective
  * Out of the 11 examples of 'great' being use as an adjective, options 1-3 refer to
    * "size"
    * "relative largeness"
    * a description of something that is "large in number or measure" 
    * (insert citation here)
  * Options 8-11 can also be dismissed as they include:
    * descriptions of family relationships
    * duration
    * distinguishing locations (option 10)
    * magnitude of emotion
  * Options 4-7 seem like they are more feasible options, but 5b, 5c and 7b can also be safely removed, as they refer to:
    * aristocratic folk
    * delineation in titles of chief members of a society
    * enthusiasm over a subject
    
This leaves us with defining 'great' as one or more of the following:

  * distinguished
  * significantly superior in character or quality; noble in nature
  * remarkably skilled
      * I am including this as an option, as national rankings in performance can be a feasible way to qualify how great a country is
      
      
These three possible definitions could be what make America great in the eyes of the MAGA community -- chances are, perceptions about America's status on all 3 of these play a role in creating this feeling. 


--- Should I look up 'great' in reference countries as well, and not just 'great' in a vacuum; additionally, I can possible do some text scraping to see at large how the word 'great' is attached to America's quilification, and to other nations as well ---

With that being said, we have successfully determined on what grounds we can test America's greatness going forward. However, before we do that, we have to figure out when the America, as it's conceptualized today, began.
  
    


## When to begin? {-}





Although I may interject pieces of history prior to 1776 that prove to be relevant, the bulk of my work will begin there. My reasoning is two fold:

  1. Simplicity. This decision is partially arbitrary, as the nation's political, cultural, economical, and social patterns didn't pop into existence at our nation's inception, and as such would be delving into world and European history spanning centuries.
  2. The 'MAGA' phrase itself indicates that we should make "Make *America* Great Again", and as such, I will be sifting through American history to find the time period that America was great. 
  
Additionally, I will also seak to provide some guidelines on how we can operationalize, or define, the word 'great' in the context of evaluating a countries history. 